### ISSUE TITLE
for using this code

### ISSUE THREAD

**Issue by HayongLee** [PSNB92/Tetris#2]
Hi there, I'm university student.

I want to use your Tetris code for our Lecture of Open source software project.

It is going to be used for education purpose only.

May I get permission to use your project's license?

**Comment by FareasTony** [comment]
Sorry to say that I am not the creator of the project. I just watch the project only. Maybe you better ask the creator(I think he/she is PSNB92).

從我的 iPhone 傳送

hayong lee <notifications@github.com<mailto:notifications@github.com>> 於 2017年11月2日 12:27 寫道：


Hi there, I'm university student.

I want to use your Tetris code for our Lecture of Open source software project.

It is going to be used for education purpose only.

May I get permission to use your project's license?

**Comment by PSNB92** [comment]
Hi there,

I've added a license to the project now, so feel free to use the code for whatever purposes you want.

Just a heads up though, I wrote this shortly after I started programming, so the quality of the code is fairly poor.

**Comment by HayongLee** [comment]
thanks, I appreciate it. :)
